package(default_visibility = ["//visibility:public"])

filegroup(
    name = "scripts",
    srcs = glob([
        "**/*.sh",
    ]),
    data = [
        "//onboard/drivers/lidar_service:lidar_control_service",
        "//onboard/drivers/lidar_service:test_lidar_control_client",
    ],
)
