#  --------------------------------------------------------------------------
#  |                _     _              _____         _____                |
#  |               |  \  | |            / ____|  /\   |  __ \               |
#  |               | | \ | |  __       | (___   /  \  | |__) |              |
#  |               | |\ \| | /__\|   |  \___ \ / /\ \ |  _  /               |
#  |               | | \ \ ||    |   |   ___) / /__\ \| | \ \               |
#  |               |_|  \_\| \__/ \_/|/|_____/________\_|  \_\              |
#  |                                                                        |
#  --------------------------------------------------------------------------
#  COPYRIGHT
#  --------------------------------------------------------------------------
#
#  This software is copyright protected and proprietary to Neusoft Reach.
#  Neusoft Reach grants to you only those rights as set out in the license 
#  conditions.
#  All other rights remain with Neusoft Reach.
#  --------------------------------------------------------------------------

# Add the rest
add_subdirectory(common)
add_subdirectory(diagnostic_proxy)
add_subdirectory(diagnostic_proxy_lib)
